'''Shree Radhe'''

from doc_embeddings import run_workflow
from search import query

import gradio as gr
from gradio.themes.base import Base

with gr.Blocks(theme=Base(), title="Question-Answering") as app:
    gr.Markdown(
        """
        # Question / Answering App using Vector Search + RAG Architecture
        """)

    textbox = gr.Textbox(label="Enter your Ques:", autofocus=True)
    
    with gr.Row():
        button = gr.Button("Submit", variant="primary")

    with gr.Column():
        out1 = gr.Textbox(lines=1, max_lines=10, label="Output with Atlas Vector Search")
        out2 = gr.Textbox(lines=1, max_lines=10, label="Output generated by chaining \
            Atlas Vector Search to Langchain Retreival QA")

    button.click(query, textbox, outputs=[out1, out2])

app.launch()



